export const categories = ['All','Automation','Engineering','Growth','Creative','Operations']
export const roles = [
 {slug:'gohighlevel',name:'GoHighLevel Expert',category:'Automation',symbol:'GH',description:'Funnels, pipelines and follow-ups that work together, built around the way you sell.',deliverables:['Funnel and landing-page setup','Lead pipelines and opportunity stages','Email and SMS workflow configuration','Reporting and ongoing optimisation']},
 {slug:'crm',name:'CRM Expert',category:'Automation',symbol:'⌘',description:'A cleaner customer journey, from first conversation to the next opportunity.',deliverables:['CRM audit and data organisation','HubSpot, Zoho or custom CRM setup','Migration and integration planning','Dashboards and team documentation']},
 {slug:'business-automation',name:'Business Automation',category:'Automation',symbol:'✳',description:'Connect your everyday tools and take repetitive work out of your day.',deliverables:['Workflow discovery and process mapping','Tool integrations and automated handoffs','AI-assisted workflows with human review','Monitoring, testing and documentation']},
 {slug:'software-development',name:'Software Development',category:'Engineering',symbol:'</>',description:'Turn a business problem into a useful, thoughtfully engineered digital product.',deliverables:['Product scoping and technical planning','Web apps, dashboards and internal tools','Quality checks and release support','Maintainable code and documentation']},
 {slug:'full-stack',name:'Full-Stack Development',category:'Engineering',symbol:'{}',description:'One engineering partner for the experience, the logic and everything underneath.',deliverables:['Frontend interfaces and design systems','Backend services and database design','Authentication and integrations','Deployment and performance improvements']},
 {slug:'api-integration',name:'API Integration',category:'Engineering',symbol:'↔',description:'Let your systems talk, so your team can stop copying information between them.',deliverables:['Integration architecture','API and webhook connections','Error handling and data validation','Integration documentation']},
 {slug:'wordpress',name:'WordPress Development',category:'Engineering',symbol:'W',description:'A fast, manageable website your team can keep moving forward.',deliverables:['Custom pages and theme development','Plugin configuration and integrations','Responsive and performance improvements','Content management handover']},
 {slug:'seo',name:'SEO Expert',category:'Growth',symbol:'↗',description:'Build a stronger search foundation with technical improvements and useful content.',deliverables:['Technical and content audit','Keyword and topic planning','On-page improvements','Search performance reporting']},
 {slug:'social-media',name:'Social Media Marketing',category:'Growth',symbol:'◎',description:'Give your brand a consistent voice, a thoughtful calendar and a reason to be followed.',deliverables:['Channel and audience planning','Content calendar and publishing','Community management','Channel performance reviews']},
 {slug:'media-buying',name:'Media Buying',category:'Growth',symbol:'⌁',description:'Thoughtful paid campaigns, managed around clear objectives and measured learning.',deliverables:['Meta and Google campaign setup','Audience and creative testing','Conversion tracking review','Budget and performance reporting']},
 {slug:'content-writing',name:'Content Writing',category:'Creative',symbol:'Aa',description:'Clear, distinctive writing for the moments that matter in your customer journey.',deliverables:['Website and landing-page copy','Email sequences','Articles and long-form content','Brand voice guidelines']},
 {slug:'ui-ux',name:'UI/UX Design',category:'Creative',symbol:'◈',description:'Make complex products feel intuitive, and every interaction feel considered.',deliverables:['User flows and wireframes','High-fidelity interface design','Interactive prototypes','Design systems and developer handoff']},
 {slug:'graphic-design',name:'Graphic Design',category:'Creative',symbol:'✦',description:'A coherent visual world for your brand, across screens, campaigns and conversations.',deliverables:['Brand visual systems','Marketing and social assets','Presentation design','Reusable design templates']},
 {slug:'motion-graphics',name:'Motion Graphics',category:'Creative',symbol:'▶',description:'Give your message movement, rhythm and a little more staying power.',deliverables:['Motion concepts and storyboards','Animated brand and product graphics','Social motion assets','Platform-ready exports']},
 {slug:'2d-animation',name:'2D Animation',category:'Creative',symbol:'◇',description:'Explain your idea with expressive, carefully paced visual storytelling.',deliverables:['Concept and storyboard development','Illustrated visual assets','Explainer animation','Final edits and exports']},
 {slug:'video-editing',name:'Video Editing',category:'Creative',symbol:'▥',description:'Turn raw footage into a story people want to stay with.',deliverables:['Narrative editing','Captions and sound finishing','Colour adjustments','Long-form and short-form versions']},
 {slug:'virtual-assistant',name:'Virtual Assistants',category:'Operations',symbol:'✓',description:'Dependable support for the everyday work that keeps your business moving.',deliverables:['Inbox and calendar support','Research and administrative tasks','Customer follow-up coordination','Documented recurring processes']},
 {slug:'data-entry',name:'Data Entry Specialist',category:'Operations',symbol:'▦',description:'Organised, checked and usable data, without the manual work on your plate.',deliverables:['Data entry and organisation','Data cleaning and formatting','Quality checks','Spreadsheet and CRM updates']},
 {slug:'project-management',name:'Project Management',category:'Operations',symbol:'⏱',description:'Clear priorities, organised delivery and fewer things falling between the cracks.',deliverables:['Project plans and milestones','Team and task coordination','Progress reporting','Risk and dependency tracking']}
]
