export { PageIntro, EndCTA, Mark } from './page-components/PageShared'
export { ServicesPage } from './page-components/ServicesPage'
export { ServiceDetail } from './page-components/ServiceDetail'
export { AutomationPage } from './page-components/AutomationPage'
export { HirePage } from './page-components/HirePage'
export { ContactPage } from './page-components/ContactPage'
export { NotFound } from './page-components/NotFoundPage'
